<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class ProfessionalSeeder extends Seeder
{
    public function run(): void
    {        

        // Desactiva FKs → truncate seguro y rápido
        Schema::disableForeignKeyConstraints();
        DB::table('professionals')->truncate();
        Schema::enableForeignKeyConstraints();
        
        $professionals = [
            [
                'center_id' => 1,
                'role' => 'Administració',
                'name' => 'Root',
                'surname1' => 'Toor',
                'surname2' => 'Toor',
                'dni' => 'F9876543B',
                'phone' => '+34 600 333 444',
                'email' => 'root@canserra.cat',
                'address' => 'Carrer Coordinador, 2, Barcelona',
                'employment_status' => 'Actiu',
                'cvitae' => 'Es el root',
                'user' => 'root',
                'password' => 'admin', // automatic hash
                'locker_num' => 'T001',
                'key_code' => 'KEY000',
                'status' => 1,
            ],
            [
                'center_id' => 1,
                'role' => 'Directiu',
                'name' => 'Joan',
                'surname1' => 'García',
                'surname2' => 'Martínez',
                'dni' => 'A3427812C',
                'phone' => '+34 600 111 222',
                'email' => 'joan.garcia@canserra.cat',
                'address' => 'Carrer Director, 1, Barcelona',
                'employment_status' => 'Actiu',
                'cvitae' => 'Experiència en gestió de centres educatius',
                'user' => 'joan.garcia',
                'password' => 'admin',
                'locker_num' => 'T002',
                'key_code' => 'KEY001',
                'status' => 1,
            ],
            [
                'center_id' => 1,
                'role' => 'Administració',
                'name' => 'Maria',
                'surname1' => 'López',
                'surname2' => 'Fernández',
                'dni' => 'F9876544C',
                'phone' => '+34 600 333 445',
                'email' => 'maria.lopez@canserra.cat',
                'address' => 'Carrer Coordinador, 2, Barcelona',
                'employment_status' => 'Actiu',
                'cvitae' => 'Especialista en coordinació pedagògica',
                'user' => 'maria.lopez',
                'password' => 'admin',
                'locker_num' => 'T003',
                'key_code' => 'KEY002',
                'status' => 1,
            ],
            [
                'center_id' => 2,
                'role' => 'Tècnic',
                'name' => 'Pere',
                'surname1' => 'Sánchez',
                'surname2' => 'Ruiz',
                'dni' => 'D1234567X',
                'phone' => '+34 600 555 666',
                'email' => 'pere.sanchez@casabadina.cat',
                'address' => 'Carrer Educador, 3, Barcelona',
                'employment_status' => 'Actiu',
                'cvitae' => 'Educador social amb experiència en joves',
                'user' => 'pere.sanchez',
                'password' => 'admin',
                'locker_num' => 'T004',
                'key_code' => 'KEY003',
                'status' => 1,
            ],
            [
                'center_id' => 1,
                'role' => 'Tècnic',
                'name' => 'Anna',
                'surname1' => 'Torres',
                'surname2' => 'Vargas',
                'dni' => 'B8765432Z',
                'phone' => '+34 600 777 888',
                'email' => 'anna.torres@canserra.cat',
                'address' => 'Carrer Psicòleg, 4, Barcelona',
                'employment_status' => 'Suplència',
                'cvitae' => 'Psicòloga clínica especialitzada en adolescents',
                'user' => 'anna.torres',
                'password' => 'admin',
                'locker_num' => 'T005',
                'key_code' => 'KEY004',
                'status' => 1,
            ],
            [
                'center_id' => 1,
                'role' => 'Tècnic',
                'name' => 'Carles',
                'surname1' => 'Molina',
                'surname2' => 'González',
                'dni' => 'C4567891Y',
                'phone' => '+34 600 999 000',
                'email' => 'carles.molina@canserra.cat',
                'address' => 'Carrer Tècnic, 5, Barcelona',
                'employment_status' => 'Actiu',
                'cvitae' => 'Tècnic en integració social',
                'user' => 'carles.molina',
                'password' => 'admin',
                'locker_num' => 'T006',
                'key_code' => 'KEY005',
                'status' => 1,
            ],
            [
                'center_id' => 1,
                'role' => 'Administració',
                'name' => 'Ruben',
                'surname1' => 'Gallardo',
                'surname2' => 'Mancha',
                'dni' => 'G1234567C',
                'phone' => '+34 600 111 222',
                'email' => 'ruben.gallardo@canserra.cat',
                'address' => 'Carrer Coordinador, 10, Barcelona',
                'employment_status' => 'Actiu',
                'cvitae' => 'Responsable de projectes',
                'user' => 'ruben.gallardo',
                'password' => 'admin', // automatic hash
                'locker_num' => 'T007',
                'key_code' => 'KEY006',
                'status' => 1,
            ],
            [
                'center_id' => 1,
                'role' => 'Administració',
                'name' => 'Yoel',
                'surname1' => 'Berjaga',
                'surname2' => 'Garcia',
                'dni' => 'H2345678D',
                'phone' => '+34 600 222 333',
                'email' => 'yoel.berjaga@canserra.cat',
                'address' => 'Carrer Coordinador, 12, Barcelona',
                'employment_status' => 'Actiu',
                'cvitae' => 'Tècnic administratiu',
                'user' => 'yoel.berjaga',
                'password' => 'admin', // automatic hash
                'locker_num' => 'T008',
                'key_code' => 'KEY007',
                'status' => 1,
            ],
            [
                'center_id' => 2,
                'role' => 'Tècnic', // Educador → Tècnic
                'name' => 'Laura',
                'surname1' => 'Ribas',
                'surname2' => 'Font',
                'dni' => 'I3456789E',
                'phone' => '+34 600 444 555',
                'email' => 'laura.ribas@casabadina.cat',
                'address' => 'Carrer Educador, 6, Barcelona',
                'employment_status' => 'Actiu',
                'cvitae' => 'Educadora amb experiència en diversitat funcional',
                'user' => 'laura.ribas',
                'password' => 'admin',
                'locker_num' => 'T009',
                'key_code' => 'KEY008',
                'status' => 1,
            ],
            [
                'center_id' => 2,
                'role' => 'Tècnic', // Psicòleg → Tècnic
                'name' => 'David',
                'surname1' => 'Casas',
                'surname2' => 'Alonso',
                'dni' => 'J9876541K',
                'phone' => '+34 600 555 222',
                'email' => 'david.casas@casabadina.cat',
                'address' => 'Carrer Salut, 7, Barcelona',
                'employment_status' => 'Actiu',
                'cvitae' => 'Psicòleg infantil amb experiència clínica',
                'user' => 'david.casas',
                'password' => 'admin',
                'locker_num' => 'T010',
                'key_code' => 'KEY009',
                'status' => 1,
            ],
            [
                'center_id' => 1,
                'role' => 'Directiu', // Coordinador → Directiu
                'name' => 'Marta',
                'surname1' => 'Domènech',
                'surname2' => 'Puig',
                'dni' => 'K6543219L',
                'phone' => '+34 600 888 111',
                'email' => 'marta.domenech@canserra.cat',
                'address' => 'Carrer Coordinador, 9, Barcelona',
                'employment_status' => 'Actiu',
                'cvitae' => 'Coordinadora de programes educatius',
                'user' => 'marta.domenech',
                'password' => 'admin',
                'locker_num' => 'T011',
                'key_code' => 'KEY010',
                'status' => 1,
            ],
            [
                'center_id' => 2,
                'role' => 'Tècnic',
                'name' => 'Jordi',
                'surname1' => 'Pujol',
                'surname2' => 'Serra',
                'dni' => 'L2345678M',
                'phone' => '+34 600 222 999',
                'email' => 'jordi.pujol@casabadina.cat',
                'address' => 'Carrer Educador, 8, Barcelona',
                'employment_status' => 'Actiu',
                'cvitae' => 'Formador en inserció laboral',
                'user' => 'jordi.pujol',
                'password' => 'admin',
                'locker_num' => 'T012',
                'key_code' => 'KEY011',
                'status' => 1,
            ],
            [
                'center_id' => 1,
                'role' => 'Administració',
                'name' => 'Cristina',
                'surname1' => 'Navarro',
                'surname2' => 'Blanco',
                'dni' => 'M4567892N',
                'phone' => '+34 600 333 777',
                'email' => 'cristina.navarro@canserra.cat',
                'address' => 'Carrer Coordinador, 11, Barcelona',
                'employment_status' => 'Baixa',
                'cvitae' => 'Gestora documental',
                'user' => 'cristina.navarro',
                'password' => 'admin',
                'locker_num' => 'T013',
                'key_code' => 'KEY012',
                'status' => 1,
            ],
            [
                'center_id' => 1,
                'role' => 'Tècnic', // Educador → Tècnic
                'name' => 'Albert',
                'surname1' => 'Fernández',
                'surname2' => 'Ortega',
                'dni' => 'N7894561P',
                'phone' => '+34 600 555 888',
                'email' => 'albert.fernandez@canserra.cat',
                'address' => 'Carrer Educador, 14, Barcelona',
                'employment_status' => 'Actiu',
                'cvitae' => 'Educador juvenil amb 10 anys d\'experiència',
                'user' => 'albert.fernandez',
                'password' => 'admin',
                'locker_num' => 'T014',
                'key_code' => 'KEY013',
                'status' => 1,
            ],
            [
                'center_id' => 2,
                'role' => 'Directiu',
                'name' => 'Núria',
                'surname1' => 'Roca',
                'surname2' => 'Vidal',
                'dni' => 'O3456123Q',
                'phone' => '+34 600 444 222',
                'email' => 'nuria.roca@casabadina.cat',
                'address' => 'Carrer Director, 3, Barcelona',
                'employment_status' => 'Actiu',
                'cvitae' => 'Directora adjunta del centre',
                'user' => 'nuria.roca',
                'password' => 'admin',
                'locker_num' => 'T015',
                'key_code' => 'KEY014',
                'status' => 1,
            ],
            [
                'center_id' => 1,
                'role' => 'Tècnic', // Psicòleg → Tècnic
                'name' => 'Sergi',
                'surname1' => 'Carreras',
                'surname2' => 'Gil',
                'dni' => 'P1237894R',
                'phone' => '+34 600 123 456',
                'email' => 'sergi.carreras@canserra.cat',
                'address' => 'Carrer Salut, 10, Barcelona',
                'employment_status' => 'Actiu',
                'cvitae' => 'Psicòleg especialitzat en conducta',
                'user' => 'sergi.carreras',
                'password' => 'admin',
                'locker_num' => 'T016',
                'key_code' => 'KEY015',
                'status' => 1,
            ],
            [
                'center_id' => 1,
                'role' => 'Administració',
                'name' => 'Paula',
                'surname1' => 'Moreno',
                'surname2' => 'Soler',
                'dni' => 'Q5678123S',
                'phone' => '+34 600 321 654',
                'email' => 'paula.moreno@canserra.cat',
                'address' => 'Carrer Coordinador, 15, Barcelona',
                'employment_status' => 'Suplència',
                'cvitae' => 'Secretària de direcció',
                'user' => 'paula.moreno',
                'password' => 'admin',
                'locker_num' => 'T017',
                'key_code' => 'KEY016',
                'status' => 1,
            ],
            [
                'center_id' => 2,
                'role' => 'Tècnic',
                'name' => 'Oriol',
                'surname1' => 'Prats',
                'surname2' => 'Marín',
                'dni' => 'R2314657T',
                'phone' => '+34 600 222 111',
                'email' => 'oriol.prats@casabadina.cat',
                'address' => 'Carrer Educador, 16, Barcelona',
                'employment_status' => 'Actiu',
                'cvitae' => 'Tècnic en TIC aplicades a l\'educació',
                'user' => 'oriol.prats',
                'password' => 'admin',
                'locker_num' => 'T018',
                'key_code' => 'KEY017',
                'status' => 1,
            ],
            [
                'center_id' => 2,
                'role' => 'Tècnic', // Educador → Tècnic
                'name' => 'Clara',
                'surname1' => 'Vilaseca',
                'surname2' => 'Esteve',
                'dni' => 'S7896543U',
                'phone' => '+34 600 987 654',
                'email' => 'clara.vilaseca@casabadina.cat',
                'address' => 'Carrer Educador, 18, Barcelona',
                'employment_status' => 'Actiu',
                'cvitae' => 'Educadora social en programes familiars',
                'user' => 'clara.vilaseca',
                'password' => 'admin',
                'locker_num' => 'T019',
                'key_code' => 'KEY018',
                'status' => 1,
            ],
            [
                'center_id' => 1,
                'role' => 'Administració',
                'name' => 'Marc',
                'surname1' => 'Requena',
                'surname2' => 'Costa',
                'dni' => 'T1112223V',
                'phone' => '+34 600 111 555',
                'email' => 'marc.requena@canserra.cat',
                'address' => 'Carrer Coordinador, 19, Barcelona',
                'employment_status' => 'Actiu',
                'cvitae' => 'Assistent administratiu amb experiència en RRHH',
                'user' => 'marc.requena',
                'password' => 'admin',
                'locker_num' => 'T020',
                'key_code' => 'KEY019',
                'status' => 1,
            ],
            [
                'center_id' => 1,
                'role' => 'Directiu',
                'name' => 'Directiu',
                'surname1' => 'Directiu',
                'surname2' => 'Directiu',
                'dni' => 'U1234567W',
                'phone' => '+34 600 000 001',
                'email' => 'directiu@canserra.cat',
                'address' => 'Carrer Directiu, 1, Barcelona',
                'employment_status' => 'Actiu',
                'cvitae' => 'Usuari directiu',
                'user' => 'directiu',
                'password' => 'admin', // automatic hash
                'locker_num' => 'T021',
                'key_code' => 'KEY020',
                'status' => 1,
            ],
            [
                'center_id' => 1,
                'role' => 'Tècnic',
                'name' => 'Tecnic',
                'surname1' => 'Tècnic',
                'surname2' => 'Tècnic',
                'dni' => 'V2345678X',
                'phone' => '+34 600 000 002',
                'email' => 'tecnic@canserra.cat',
                'address' => 'Carrer Tecnic, 1, Barcelona',
                'employment_status' => 'Actiu',
                'cvitae' => 'Usuari tècnic',
                'user' => 'tecnic',
                'password' => 'admin', // automatic hash
                'locker_num' => 'T022',
                'key_code' => 'KEY021',
                'status' => 1,
            ],
            [
                'center_id' => 1,
                'role' => 'Gerent',
                'name' => 'Gerent',
                'surname1' => 'Gerent',
                'surname2' => 'Gerent',
                'dni' => '94162175Z',
                'phone' => '+34 600 000 002',
                'email' => 'gerent@canserra.cat',
                'address' => 'Carrer Gerent, 1, Barcelona',
                'employment_status' => 'Actiu',
                'cvitae' => 'Usuari gerent',
                'user' => 'gerent',
                'password' => 'admin', // automatic hash
                'locker_num' => 'T023',
                'key_code' => 'KEY022',
                'status' => 1,
            ],
            [
                'center_id' => 1,
                'role' => 'Administració',
                'name' => 'Administració',
                'surname1' => 'Administració',
                'surname2' => 'Administració',
                'dni' => '93486541M',
                'phone' => '+34 600 000 002',
                'email' => 'administracio@canserra.cat',
                'address' => 'Carrer Gerent, 1, Barcelona',
                'employment_status' => 'Actiu',
                'cvitae' => 'Usuari administracio',
                'user' => 'admin',
                'password' => 'admin', // automatic hash
                'locker_num' => 'T023',
                'key_code' => 'KEY022',
                'status' => 1,
            ],
        ];

        // Hash de passwords ANTES de insertar
        foreach ($professionals as &$p) {
            // $p['password'] = Hash::make($p['password']);
            $p['password'] = Hash::make($p['password'], ['rounds' => 4]);
        }

        DB::table('professionals')->insert($professionals);
    }
}
